kind: pipeline
type: docker
name: silent-shard-dapp-runner

steps:
- name: greeting
  image: node:18
  environment:
    REACT_APP_SNAP_ID:
      from_secret: REACT_APP_SNAP_ID
    PASSWORD:
      from_secret: docker_password
  commands:
  - apt update && apt install p7zip-full
  - echo $REACT_APP_SNAP_ID