stages: 
  - build-artifact
  - deploy-staging
  - deploy-prod

build-artifact:
  stage: build-artifact
  only:
    - main
  tags:
    - dapp-builder
  script:
    - cat $ENV > .env
    - npm i
    - REACT_APP_MIX_PANEL_TOKEN=$REACT_APP_MIX_PANEL_TOKEN CI=false npm run build
    - 7z a ./dapp-v2.7z ../dapp-v2
  artifacts:
    paths:
      - ./dapp-v2.7z
    expire_in: 1 week

build-artifact-stage:
  stage: build-artifact
  only:
    - staging
  tags:
    - dapp-builder
  script:
    - cat $ENV_STAGING > .env
    - npm i
    - REACT_APP_MIX_PANEL_TOKEN=$REACT_APP_MIX_PANEL_TOKEN CI=false npm run build
    - 7z a ./dapp-v2.7z ../dapp-v2
  artifacts:
    paths:
      - ./dapp-v2.7z
    expire_in: 1 week

deploy-staging: 
  stage: deploy-staging
  only:
    - staging
  tags:
    - dapp-v2-deployer-stage
  dependencies:
    - build-artifact-stage
  script: 
    - mv dapp-v2.7z /opt/
    - cd /opt/
    - rm -r dapp-v2
    - 7z x dapp-v2.7z
    - sudo systemctl restart dapp-v2-staging.service

deploy-prod: 
  stage: deploy-prod
  only:
    - main
  tags:
    - dapp-v2-deployer
  script: 
    - rsync -avP ../dapp-v2 /opt/app/dapp-v2
    - cd /opt/app/dapp-v2/dapp-v2/
    - npm i
    - REACT_APP_MIX_PANEL_TOKEN=$REACT_APP_MIX_PANEL_TOKEN CI=false npm run build
    - sudo systemctl restart dapp-v2.service




