name: Build and Deploy

on:
  push:
    branches:
      - actions

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          npm install

      - name: Build artifact
        run: |
          cat $ENV > .env
          REACT_APP_MIX_PANEL_TOKEN=$REACT_APP_MIX_PANEL_TOKEN CI=false npm run build
          7z a ./dapp-v2.7z ../silent-shard-dapp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dapp-v2
          path: ./dapp-v2.7z
          
  deploy-staging:
    runs-on: dapp-v2-stagin
    needs: build-and-deploy
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dapp-v2
          path: ./dapp-v2
      - name: Build artifact
        run: |
          mv ./dapp-v2/dapp-v2.7z /opt/
          cd /opt/
          rm -r dapp-v2
          7z x dapp-v2.7z
        #   sudo systemctl restart dapp-v2-staging.service
  
#       # Add steps to deploy to staging environment

#   deploy-prod:
#     runs-on: ubuntu-latest
#     needs: build-and-deploy
#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: dapp-v2
#           path: ./dapp-v2.7z