name: Build and Deploy

on:
  push:
    branches:
      - actions

jobs:
  build-and-deploy-staging:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          npm install

      - name: Build artifact
        run: |
          cat $ENV_STAGING > .env
          REACT_APP_MIX_PANEL_TOKEN=$REACT_APP_MIX_PANEL_TOKEN CI=false npm run build
          7z a ./dapp-v2.7z ../silent-shard-dapp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dapp-v2
          path: ./dapp-v2.7z
          
  deploy-staging:
    runs-on: dapp-v2-stagin
    needs: build-and-deploy-staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dapp-v2
          path: ./dapp-v2
      - name: Build artifact
        run: |
          mv ./dapp-v2/dapp-v2.7z /opt/
          cd /opt/
          [ -d "dapp-v2" ] && rm -r "dapp-v2" 
          7z x dapp-v2.7z
          sudo systemctl restart dapp-v2-staging.service
